/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/**
 *
 * @author nisrienmahri
 */
public class AdminMainPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainPage
     * @throws java.lang.ClassNotFoundException
     */
    public AdminMainPage() throws ClassNotFoundException {
        initComponents();       
        populateTable();
    }
public void populateTable() throws ClassNotFoundException { 
        jTable1.getTableHeader().setOpaque(false);
        
    final String url = "jdbc:mysql://localhost:8889/FinalProject";
    final String user = "root";
    final String password = "root";
    final String QUERY = "SELECT * FROM Schools";
    
     try{
    java.sql.Connection conn = FinalProject.getConnection();
    java.sql.Statement state = conn.createStatement();
                
    String sql = "SELECT * FROM Schools";
    state.execute(sql);
                
    ResultSet rs = state.executeQuery(sql);
    
    String column[]= {"SchoolName","Location", "EducationalStage"};  
    DefaultTableModel TableModel = new DefaultTableModel(column, 0);
    
    while (rs.next()){
    String schoolname = rs.getString("SchoolName");
    String location = rs.getString("Location");
    String edstage = rs.getString("EducationalStage");
    
    Object[] data = {schoolname, location, edstage};
    TableModel.addRow(data);
    }
    jTable1.setModel(TableModel);
    }catch (SQLException e) {
        System.out.println("error:" + e);  
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        schoolnametf = new javax.swing.JTextField();
        locationtf = new javax.swing.JTextField();
        edstagetf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "School Name", "Location", "Educational Stage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 402));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("List of Schools");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 220, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 90, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 80, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Location : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 249, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Educational Stage : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 299, 117, -1));

        schoolnametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolnametfActionPerformed(evt);
            }
        });
        getContentPane().add(schoolnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 201, 179, -1));

        locationtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationtfActionPerformed(evt);
            }
        });
        getContentPane().add(locationtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 246, 179, -1));

        edstagetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edstagetfActionPerformed(evt);
            }
        });
        getContentPane().add(edstagetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 296, 179, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("School Name : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 204, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 90, 30));

        jButton4.setText("View Enrollment");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 160, 30));

        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Screen Shot 2023-01-31 at 08.08.00.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
        String schoolname = schoolnametf.getText();
        String location = locationtf.getText();
        String edstage = edstagetf.getText();
        if (schoolname.isBlank() || location.isBlank()|| edstage.isBlank()) {
           JOptionPane.showMessageDialog(null, "School Name, Location, or Educational Stage is empty");
            } else {
            try {
                java.sql.Connection conn = FinalProject.getConnection();

                PreparedStatement prep = conn.prepareStatement ("INSERT INTO Schools(SchoolName, Location, EducationalStage) VALUES (?, ?, ?)");
                        
                prep.setString(1, schoolname);
                prep.setString(2, location);
                prep.setString(3, edstage);
                prep.execute();
                JOptionPane.showMessageDialog(null, "Data inserted successfully");
                
               // java.sql.Statement state = conn.createStatement();
               // state = conn.createStatement ("UPDATE Schools SET SchoolName = '" + schoolname + "', Location = '" + location + "', EducationalStage = '" + edstage + "' WHERE company = '"+company+"'");
                
                populateTable();
                
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
            String name = schoolnametf.getText();
            String location = locationtf.getText();
            String edstage = edstagetf.getText();
            
            try {
            Statement s = FinalProject.getConnection().createStatement();
            s.executeUpdate("UPDATE Schools SET Location = '"+location+"', EducationalStage = '"+edstage+"' WHERE SchoolName = '"+name+"'");
             populateTable();
            } catch (Exception e) {
                System.out.println(e);
            }            
            
        JOptionPane.showMessageDialog(rootPane, "The data has been updated", "Successful Update", JOptionPane.INFORMATION_MESSAGE);   
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void schoolnametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolnametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolnametfActionPerformed

    private void locationtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationtfActionPerformed

    private void edstagetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edstagetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edstagetfActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        String a = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String b = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String c = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        
        schoolnametf.setText(a);
        locationtf.setText(b);
        edstagetf.setText(c);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
    try {
        java.sql.Connection conn = FinalProject.getConnection();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        int modelRow = jTable1.convertRowIndexToModel( row );
        model.removeRow( modelRow );
        
        String sql = "DELETE FROM Schools WHERE SchoolName = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString( 1, schoolnametf.getText() );
        stmt.executeUpdate();
        stmt.close();
        JOptionPane.showMessageDialog(null, "Data deleted successfully");
        
    } catch (HeadlessException | SQLException e) {
        System.out.println(e);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        
        
        try {
            new AdminEnrollment().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try {
            new LogIn().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminMainPage().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminMainPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edstagetf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField locationtf;
    private javax.swing.JTextField schoolnametf;
    // End of variables declaration//GEN-END:variables
}
